version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: fridge_user
      POSTGRES_PASSWORD: secret_pass
      POSTGRES_DB: fridge_perf_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fridge_perf_db
      SPRING_DATASOURCE_USERNAME: fridge_user
      SPRING_DATASOURCE_PASSWORD: secret_pass

volumes:
  pgdata: